### ISSUE TITLE
The main field in the package.json of `color2k@1.2.0` points to non-existent TypeScript file

### ISSUE THREAD

**Issue by ifiokjr** [ricokahler/color2k#343]
### Description

The latest release [here](https://unpkg.com/browse/color2k@1.2.0/package.json) breaks in common js environments. I'm running into issues when running tests in `jest`. 

The `main` field is pointing to `"./dist/index.ts"` as seen in the [package.json](https://unpkg.com/browse/color2k@1.2.0/package.json) hosted via unpkg.

**Comment by ricokahler** [comment]
Thanks for catching this. Definitely a typo. A new build will be out in a few minutes with a fix

**Comment by ifiokjr** [comment]
Thanks for moving so quickly and great library by the way! 

I'm using it in the currently unreleased beta branch of https://github.com/remirror/remirror

**Comment by ricokahler** [comment]
Of course. The irony of this is that the bug came during the refactor to better CI (semantic-release) and build tools (microbundle) but at least it meant the fix was easy to get out there.

Thanks for the kind words. it's exciting to see color2k in remirror! Feel free to send any feedback along if you run into anything else.
